bnb-chain/opbnb

.github/workflows/docker-release.yml

add the ci code used to package and release docker images
Execution effect:
Note: 
Need to open the write permission of github_token, path: settings->Actions->General->Workflow permissions

ci: add the ci code used to package and release docker images

---

assets/mainnet/rollup.json

The Mainnet assets for running full nodes.
Check the [doc](https://docs.bnbchain.org/opbnb-docs/docs/tutorials/running-a-mainnet-node) for the detailed guide.

chore: add mainnet assets for running nodes

---

op-node/metrics/metrics.go
op-node/p2p/notifications.go

When we use DNS to specify the addresses of staticPeers, there may be a situation where one peer corresponds to multiple connections. Therefore, the same peer may trigger the `Connected` or the `Disconnected` event of `Notifiee` multiple times. This will cause inaccurate peerCount statistics. In addition, restarting the op-node service may also cause statistical problems. Because peerCount is a gauge type indicator, if the `Disconnected` event cannot be processed in time when the service is closed, peerCount may retain incorrect data and will not decrease to 0.
In order to minimize the impact of duplicate events and server restarts, we should use `Gauge.Set(float64)` instead of the currently used `Inc*()` and `Dec*()` methods. Getting the length of the peers array stored in the `Network` …

bugfix(op-node): fix the issue of inaccurate peerCount Metric

---

op-batcher/batcher/channel_manager.go

cherry pick op-batcher race condition fix pr from upstream: https://github.com/ethereum-optimism/optimism/pull/6878

op-batcher: Make channel manager safe for concurrent use

---

op-node/p2p/sync.go

The Req-Resp protocol is primarily employed to synchronize recent blocks that have not yet been submitted to L1.
Given that the _channel timeout_ on the mainnet is set to `1200`, and considering the L1 block interval of 3 seconds, the _channel timeout_ can effectively be regarded as a timeframe of 3600s.
As a result, I have configured the capacity of the `quarantine` to be `3600`, which can help mitigate the probability of eviction from the quarantine, so that to speed up the sync process.
----
Weakness of current Req-Resp implementation:
1. Trust chain must proceed from back to front   ←   Only Gossip blocks carry with sequencer's signature
2. During one round of `RequestL2Range`, for each number, alt-sync only requests to single peer
3. Lacks of re-try for request failures. Alt-sync …

perf: reduce quarantine eviction

---

op-node/sources/receipts.go

Add a new type of rpckind: bsc_fullnode.
This type corresponds to a new method for retrieving receipts: eth_getTransactionReceiptsByBlockNumber.
This method retrieves all receipts within a block height at once, providing high performance. However, it is limited to L1 endpoints that support the bsc fullnode interface.
Original default method: EthGetTransactionReceiptBatch performs poorly when the L1 network is busy.
Add the following parameters to op-node
--l1.rpckind=bsc_fullnode
* Add a new type of rpckind: bsc_fullnode
* EthGetTransactionReceiptsByBlockNumber logic in RunAltMethod function

feat(op-node): add rpcKind bsc_fullnode for eth_getTransactionReceiptsByBlockNumber

---

op-node/sources/eth_client.go
op-node/sources/l1_client.go

This PR changed rpc method of get finalized L1 block
There are two methods to get finalized block on BSC:
1. eth_getBLockByNumber with finalized tag
2. eth_getFinalizedBlock
first one only return the fastFinalizedHeader, which is not exactly finalizedHeader when fast finality action failed.
second one is a bsc specific rpc method to always return right finalizedHeader.
currently we used first one, and we should use second one instead
N/A
This PR changes l1Client to use second method instead of first one

fix(op-node): l1 client use eth_getFinalizedBlock to get finalized block

---

op-node/sources/l1_client.go

Fix op-e2e test ci
currently op-e2e use[ go-ethereum in memory](https://github.com/bnb-chain/opbnb/blob/b1c385832be8cbd7f1598122de22fbc594fdfaca/op-e2e/actions/l1_replica.go#L33) as L1, so bsc specific rpc method eth_getFinalizedBlock is not supported
this pr fallback to not use eth_getFinalizedBlock if it's not supported
L1Client fallback to not use eth_getFinalizedBlock if it's not supported

fix(op-e2e): fallback to not use bsc specific method eth_getFinalizedBlock

---

op-batcher/batcher/config.go
op-batcher/batcher/driver.go
op-batcher/flags/flags.go
op-batcher/metrics/metrics.go
op-batcher/metrics/noop.go
op-e2e/actions/fallback_client_test.go
op-e2e/actions/l1_miner.go
op-e2e/actions/l1_replica.go
op-node/flags/flags.go
op-node/metrics/metrics.go
op-node/node/client.go
op-node/node/node.go
op-node/sources/fallback_client.go
op-proposer/flags/flags.go
op-proposer/metrics/metrics.go
op-proposer/metrics/noop.go
op-proposer/proposer/config.go
op-proposer/proposer/l2_output_submitter.go
op-service/client/ethclient.go
op-service/client/fallback_client.go
op-service/metrics/balance.go
op-service/txmgr/cli.go
op-service/txmgr/metrics/noop.go
op-service/txmgr/metrics/tx_metrics.go
op-service/txmgr/txmgr.go

The FallbackClient is designed to automatically switch to an alternative L1 endpoint when the current one encounters issues, and revert back once the primary endpoint is functional again.
The core logic operates as follows: When an error occurs, it is recorded until either the error count surpasses a predetermined threshold or the count is reset by a timer that executes once per minute. If the threshold is exceeded within a one-minute span, it suggests the L1 endpoint has become unreliable, prompting the system to select the next address in the L1 URL. A new RPC client is then created to replace the current one. Simultaneously, a separate Goroutine monitors the initial endpoint's health and, when deemed stable, reverts back to its use.
As the clients employed in op-node and …

feat(op-node/op-batcher/op-proposer): add fallbackClient

---

op-node/p2p/node.go
op-node/p2p/sync_test.go

When the staticPeer is configured with a DNS address (such as `/dns/xxx.com/tcp/xxx/p2p/xxx`), a peer can obtain multiple IP addresses through domain name resolution. However, in Libp2p, dialing concurrently can result in one peer corresponding to multiple connections, which is exacerbated by multiple IP addresses. If one of the connections is disconnected due to an unstable network or other reasons, the `Notifiee.Disconnected` event is triggered. At this time, the peer is removed from the syncClient, and the processing flow of the peerLoop exits. The log displays the message `stopped syncing loop of peer`. However, the peer still has other connections that can be used for p2p synchronization. Therefore, we should not remove this peer unless we determine that all of its connections are …

bugfix(op-node): syncClient incorrectly removes peer issue

---

op-e2e/actions/l2_batcher_test.go
op-e2e/actions/l2_sequencer.go
op-e2e/actions/l2_verifier.go
op-e2e/actions/l2_verifier_test.go
op-e2e/actions/reorg_test.go
op-e2e/actions/sync_test.go
op-e2e/actions/system_config_test.go
op-node/eth/sync_status.go
op-node/flags/flags.go
op-node/node/config.go
op-node/node/node.go
op-node/node/server_test.go
op-node/rollup/derive/engine_queue.go
op-node/rollup/derive/engine_queue_test.go
op-node/rollup/derive/error.go
op-node/rollup/derive/pipeline.go
op-node/rollup/driver/driver.go
op-node/rollup/driver/state.go
op-node/rollup/sync/config.go
op-node/rollup/sync/start.go
op-node/rollup/sync/start_test.go
op-node/service.go
op-node/testutils/random.go
op-program/client/driver/driver.go
specs/exec-engine.md

**Description**
This feature is related to [PR #6243](https://github.com/ethereum-optimism/optimism/pull/6243). 
**Rationale**
Triggering the Execution Engine’s P2P sync for a faster sync.
**Example**
NA
**Changes**
1. add config to trigger engine P2P sync
2. optimize engine queue reset check

feat: engine p2p sync feature

---

.github/workflows/reviewer.yml

Implemented a feature to automatically assign two reviewers to a PR using a bot.
This automation streamlines the review process, ensuring that each PR is reviewed by at least two team members, thereby maintaining code quality and consistency.
Upon PR submission, the bot automatically assigns two reviewers from the team.
* Created a script for the bot to randomly select and assign two reviewers to a PR.
* Integrated the bot script with the existing CI/CD pipeline.

chore(ci): randomly assign 2 reviewers with bot

---

.github/workflows/ci.yml

execute op-e2e-http-test and op-e2e-ws-test serially
These two CI sometimes fail because the CI machine specifications is low. We need to let CI execute serially to increase the success rate of ci execution.
none
- execute op-e2e-http-test and op-e2e-ws-test serially

ci: execute op-e2e-http-test and op-e2e-ws-test serially

---

op-batcher/metrics/metrics.go
op-e2e/actions/l2_verifier.go
op-e2e/setup.go
op-e2e/system_adminrpc_test.go
op-e2e/system_test.go
op-node/flags/flags.go
op-node/node/api.go
op-node/node/config.go
op-node/node/config_persistence.go
op-node/node/config_persistence_test.go
op-node/node/node.go
op-node/node/server_test.go
op-node/rollup/driver/driver.go
op-node/rollup/driver/state.go
op-node/service.go
op-node/sources/rollupclient.go

Merge a previous PR #24 to develop branch.
The previous pull request, #24, introduced the `rpc.admin-state` flag for the op-node, enabling high availability scenarios. Initially, it only existed on a separate branch. We have now merged it into the develop branch.
Add `--rpc.admin-state=/server/admin-state.log` parameter for op-node to enable this feature.
* Add `rpc.admin-state` flag for op-node.

feat: support persist active api

---

CHANGELOG.md
op-node/chaincfg/chains.go

Add opBNB mainnet Fermat fork height.
NA
NA
* change opBNB mainnet Fermat fork height
* add v0.2.2 changelog

feat: add opbnb mainnet Fermat fork height

---

op-node/sources/fallback_client.go

I changed the threshold for fallbackClient to 10, previously 20 was too high.
We found that the threshold of 20 errors per minute is too high for nodes that are not sequencers, causing the fallbackClient to not function properly.
none
* threshold 20->10

fix(op-node): change fallback client threshold to 10 from 20

---

op-node/sources/fallback_client.go
op-service/client/fallback_client.go

fallbackClient ignores `ethereum.NotFound` errors when counting errors during error handling, as this error does not indicate any issues with the endpoint's health.
The fallbackClient in op-node and op-batcher was modified. Due to the multiple rpc methods in fallbackClient in op-batcher, it can be difficult to troubleshoot issues. Therefore, some new logs were added to facilitate future troubleshooting.
We found that the fallbackClient in op-batcher always inexplicably switches endpoints, although no request error was found in the log. After investigation, it was found that the `ethereum.NotFound` error returned by the interface when op-batcher obtained the TransactionReceipt was counted by the fallbackClient.
none
* In both op-node and op-batcher, the fallbackClient …

fix(op-node/op-batcher): fallbackClient should ignore ethereum.NotFound error

---

.github/labeler.yml
.github/workflows/labeler.yml

Due to the latest 5.0 version of the labeler component making incompatible changes to the configuration file format, our labeler ci workflow is not functioning properly. I have made fixes for this.
The latest version of the labeler component has made incompatible changes to the configuration file format, see: https://github.com/actions/labeler/releases/tag/v5.0.0
none
* Modify labeler.yml configuration file

fix(ci): fix labeler fail

---

op-node/p2p/cli/load_config.go
op-node/p2p/config.go

Add `opBNB` testnet and mainnet bootnodes in code.
Add `opBNB` testnet and mainnet bootnodes in code can facilitate the startup of new nodes.
The startup node will use the `opBNB` bootnodes by chainId including testnet and mainnet. If `p2p.bootnodes` is configured, the configured bootnodes will be used. The configured `p2p.bootnodes` have the highest priority.
Add `opBNB` testnet and mainnet bootnodes in code.

feat(op-node): add opBNB bootnodes

---

op-node/rollup/derive/engine_queue.go
op-node/sources/l1_client.go

I added pre-fetch receipt logic in the https://github.com/bnb-chain/opbnb/pull/57. However, if the L1 endpoint is not functioning well and the interface response time increases, the efficiency of pre-fetch will be significantly reduced. To address this issue, we parallelize the pre-fetch process for multiple future block heights. This allows us to achieve better performance even when the L1 endpoint is not in good condition.
To solve the problem of low L1 endpoint performance, we have added concurrent logic to improve the efficiency of pre-fetching receipts.
none
* Pre-fetch adds concurrency logic.
* The context passed into GoOrUpdatePreFetchReceipts has been modified to use the background context, as the ctx has a timeout of 3 seconds. We do not currently need a timeout …

feature(op-node): pre-fetch receipts concurrently

---

op-node/rollup/driver/sequencer.go
op-node/rollup/driver/state.go

continue optimizing sequencer step schedule 
there're still some corner cases, in which sequencer block produce may has issue:
1. if whole l1 network went down for more than maxSequencerDrift time, sequencer was unable to auto-recover after l1 network recovered
2. when high l1 network latency last for a long time(> maxSequencerDrift), sequencer will produce block but difficult to produce full block
3. when sequencer step is hot(e.g. catching up),  admin_stopSequencer operation may failed due to context timeout
this PR will fix above cases.
n/a
1. call sequencerStep() immediately rather than reset sequencerTimer
2. handle l1HeadSig before call sequencerStep() to avoid error caused by cannot find next l1 block
3. add accEmptyBlocks in sequencer.go to avoid never produce full block in corner …

optimize(op-node): continue optimizing sequencer step schedule

---

op-node/p2p/gossip.go

This PR incorporates modifications to the block validator within the op-node, which is utilized by both the sender (sequencer) and receiver. The block expiration check has been increased from 60 seconds to 20 minutes. This change was prompted by scenarios where the sequencer could not maintain a block production rate of one block per second. Under the previous validation logic, if blocks were produced slowly for a period and the anticipated block time was more than 60 seconds apart from the current time, the sequencer would fail the check and be unable to broadcast the block, preventing other nodes from syncing unsafe blocks. With this change, the time has been increased to 20 minutes. Please note that the 20-minute duration is not the time we maintain synchronization, but a relative time …

optimize: extended expire time for sequencer block broadcasting

---

op-node/rollup/derive/attributes.go
op-node/rollup/derive/engine_queue.go
op-node/rollup/derive/engine_queue_test.go
op-node/rollup/derive/l1_traversal.go
op-node/rollup/driver/metered_l1fetcher.go
op-node/rollup/driver/sequencer.go
op-node/sources/caching/cache.go
op-node/sources/caching/pre_fetch_cache.go
op-node/sources/eth_client.go
op-node/sources/l1_client.go
op-node/sources/receipts.go
op-node/testutils/mock_eth_client.go
op-node/testutils/mock_l1.go
op-program/client/l1/client.go
op-program/host/prefetcher/prefetcher.go

I implemented the first version of concurrent code to pre-fetch receipts at https://github.com/bnb-chain/opbnb/pull/100, but there are some problems that need to be fixed. Our cache is an LRU cache with a maximum capacity of 1000 items. When the goroutine implementation is changed to concurrent, the maximum capacity is quickly reached. This leads to the following problems:
1. Since the cache is LRU, the Get method will insert data of old blocks that were about to be evicted into the front of the queue, causing a large amount of useless data to accumulate in the cache while useful data is pushed out.
2. Concurrency makes it very easy for the cache to become full, resulting in old block data being quickly evicted and the cache becoming ineffective.
I made some changes. In the pre-fetched …

feat(op-node): pre-fetch receipts concurrently round 2

---

op-node/rollup/driver/origin_selector.go
op-node/rollup/driver/sequencer.go
op-node/rollup/driver/sequencer_test.go

set `attrs.NoTxPool` to `true` when sequencer is catching up to increase the speed
if op-geth tx pool is full when sequencer catching up, the speed will be affected by op-geth building full payload in background
n/a
1. set `attrs.NoTxPool` to `true` when sequencer is catching up
2. add `const lagTimeWindow` to trigger catching up mode
3. refactor to add `const buildFullBlockInterval`

optimize(op-node): increase catching up speed when sequencer lagging

---

op-batcher/batcher/config.go
op-batcher/batcher/driver.go
op-batcher/metrics/metrics.go
op-batcher/metrics/noop.go
op-proposer/metrics/metrics.go
op-proposer/metrics/noop.go
op-proposer/proposer/l2_output_submitter.go
op-service/client/ethclient.go
op-service/client/fallback_client.go
op-service/client/metrics.go
op-service/txmgr/cli.go
op-service/txmgr/metrics/noop.go
op-service/txmgr/metrics/tx_metrics.go

Currently neither op-batcher nor op-proposer has metrics related to RPC clients, so we cannot know the performance of requesting L1 and L2 endpoints. We need to solve this problem.
We add InstrumentedClient in op-service, which is responsible for collecting metrics for each method.
Example of new metrics:
op_batcher_default_rpc_client_requests_total
op_proposer_default_rpc_client_requests_total
op_batcher_default_rpc_client_request_duration_seconds_bucket
op_proposer_default_rpc_client_request_duration_seconds_bucket
* Added InstrumentedClient in op-service
* Replace the original EthClient with the newly added InstrumentedClient.
* Add necessary items to metrics in op-batcher and op-proposer.

feat(op-batcher/op-proposer): add InstrumentedClient

---

op-node/rollup/driver/state.go

remove 3s timeout context for sequencer in case stepReqCh
for 200M block gas limit, full block could has 9k+ txns and call eth_getBlockByHash to get a fullblock would timeout if we limited timeout context to 3s, which especially would happen when resetting pipeline
n/a
remove 3s timeout context for sequencer in case stepReqCh in state.go

fix(op-node): remove 3s stepCtx for sequencer

---

op-node/sources/caching/pre_fetch_cache.go
op-node/sources/l1_client.go
op-node/sources/l1_client_test.go

If L1 experiences a reorganization within 15 blocks, the pre-fetched receipts data will be useless, which will trigger the optimization in https://github.com/bnb-chain/opbnb/pull/87, and the sequencer will continue to produce blocks based on the same L1 block height instead of using the next block. In order to minimize this situation, we need to handle the case where L1 experiences a reorganization within 15 blocks.
When we detect that the hash value of the oldest block height in this round does not match the hash value of the latest block height in the previous round, it means that a reorganization has occurred in the L1 chain. We will roll back the current block height variable to 15 blocks ago to avoid problems caused by reorganization within 15 blocks. If it is a reorganization of …

fix(op-node): pre-fetching handle L1 reOrg

---

op-node/sources/l1_client.go

In https://github.com/bnb-chain/opbnb/pull/115, I added the ability to handle L1 reorganization to pre-fetching. During testing, I found that if the cache already exists, blockInfo should also be added to blockInfoChan, which avoids oldestBlockParentHash and parentHash being incorrectly set to common.hash.
Even if the cache already exists, blockInfo should be stuffed into blockInfoChan to avoid incorrect recording of the parent hash.
In addition, due to the higher reliability requirements for pre-fetching, PreFetchReceipts will continue to loop until successful after returning err.
none
* Some minor logic changes for GoOrUpdatePreFetchReceipts

fix(op-node): pre-fetching handle L1 reOrg round 2

---

.github/workflows/ci.yml
op-e2e/actions/fallback_client_test.go
op-node/sources/fallback_client.go
op-service/client/fallback_client.go

In extreme cases, all of our endpoint URLs may be unable to connect, and the `rpcInitFunc` will return an error, causing the `recoverIfFirstRpcHealth` function to not have a chance to execute. So when the endpoint URLs are restored, our currentIndex counter still points to the end of the urlList array, causing internal state confusion in the fallbackClient and permanently disabling the fallback function until the node is restarted.
We use `defer` to ensure that no matter what the situation, `recoverIfFirstRpcHealth` will be executed.
none
* Use `defer` to ensure that `recoverIfFirstRpcHealth` will always be executed regardless of the circumstances.
* Add a judgment condition to avoid mistakenly closing firstRpc with `lastRpc.Close()`, which will cause confusion in …

fix(op-node/op-batcher/op-proposer): the fallback client should always try recover

---

op-service/sources/caching/cache.go
op-service/sources/caching/pre_fetch_cache.go
op-service/sources/eth_client.go
op-service/sources/eth_client_test.go
op-service/sources/l1_client.go
op-service/sources/l1_client_test.go
op-service/sources/l2_client.go
op-service/sources/receipts_test.go
ops-bedrock/Dockerfile.l2

In https://github.com/bnb-chain/opbnb/pull/100 and https://github.com/bnb-chain/opbnb/pull/104, I modified the pre-fetch logic for receipts. Based on metrics, we found that the performance of the block info and transaction retrieval APIs is also poor when L1 load is high. We need to fetch this data in advance and put it into cache. As the InfoAndTxsByHash is called in the FetchReceipts interface, the pre-fetch logic for block info and transaction data has already been performed in the receipts. I just need to make some modifications to the existing unreasonable parts to make pre-fetch effective for block info and transactions.
LRU cache is not applicable in all cases, so I added the bool parameter isReadOrderly to EthClient. When we request L1 from our EthClient, we request the data in …

feat(op-node): pre-fetch block info and transaction

---

op-chain-ops/genesis/config.go
op-node/chaincfg/chains.go
op-node/rollup/derive/attributes.go
op-node/rollup/driver/metered_l1fetcher.go
op-node/rollup/types.go
op-node/rollup/types_test.go
op-service/bsc/compat.go

Optimize l1 gas price calculation.
The current L1 gas price is a fixed value. This value can't truly reflect the L1 gas price and needs to be adjusted. The median gas price of the latest 21 blocks(21 validators in bsc) is calculated.
n/a
* Add new `Snow` hard fork to change L1 gas price.
* Rename `OPBNBDevnet` to `OPBNBQANet` and update info.
* Optimize log description.

feat: optimize l1 gas price calculation after snow hardfork

---

.github/workflows/docker-release.yml
op-bootnode/Dockerfile

add bootnode to docker-release.yml workflow
bootnode package release is missed
n/a
1.  add bootnode to docker-release.yml workflow

chore: add bootnode to docker-release.yml workflow

---

CHANGELOG.md
op-node/chaincfg/chains.go

Add snow hardfork mainnet time.
The current L1 gas price is currently a fixed value, but it may not accurately reflect the true L1 gas price and needs to be adjusted. The median gas price of the latest 21 blocks (21 validators in BSC) will be calculated after the upcoming hardfork scheduled for April 9, 2024, at 06:00 AM UT. For more details, please refer to <https://github.com/bnb-chain/opbnb/pull/169>.
NA
* NA

feat: add snow hardfork mainnet time

---

op-node/flags/flags.go
op-node/flags/p2p_flags.go

Simplify op-node start
Currently, starting op-node requires manual setting of many parameters. In order to facilitate users to start nodes, some default configuration added for opBNB mainnet and testnet.
Currently, there are two network configurations, opBNB mainnet and testnet by default. You can select the corresponding network configuration by setting `--network= opBNBMainnet ` or `--network=opBNBTestnet`.  You also need to set some config manually:
* `--l1=L1_RPC`
* `--l2=L2_RPC`
* `--l2.jwt-secret=./jwt.txt`
* `--snapshotlog.file=./snapshot.log`
For example:
```
./geth --network= opBNBMainnet --l2.jwt-secret=./jwt.txt --l1=L1_RPC --l2=L2_RPC --snapshotlog.file=./snapshot.log
```
```
./geth --network= opBNBTestnet --l2.jwt-secret=./jwt.txt --l1=L1_RPC --l2=L2_RPC …
```

feature(op-node): simplify op-node start

---

Makefile
bedrock-devnet/README.md
bedrock-devnet/devnet/__init__.py
ops-bedrock/Dockerfile.l1
ops-bedrock/docker-compose.yml
ops-bedrock/l1-entrypoint.sh
packages/contracts-bedrock/scripts/Config.sol

After merging the code from upstream version 1.7.2, we need to make some modifications to ensure that our Devnet scripts continue to function properly. Among them, we need to test the ability to submit blobs for BSC as L1, so I have made significant changes to the Devnet deployment process for BSC.
After merging upstream code, fix our Devnet script.
After this PR, you can still use the `make devnet-up` command to start Devnet. For more details, please refer to the content of the bedrock-devnet/README.md file.
* Fix Devnet script

fix: fix devnet after 1.7.2 upstream merge

---

op-chain-ops/genesis/config.go
packages/contracts-bedrock/scripts/getting-started/config.sh

Update deployment script for `opBNB`.
The current script for deploying a new chain does not match the current code, and it also lacks some of opBNB features.
* Update config.sh.

feature: update deployment script for opBNB

---

bedrock-devnet/devnet/__init__.py
go.mod
go.sum
op-batcher/batcher/service.go
op-challenger/cmd/list_claims.go
op-challenger/cmd/list_games.go
op-challenger/cmd/utils.go
op-challenger/game/service.go
op-challenger/metrics/noop.go
op-conductor/conductor/service.go
op-e2e/actions/fallback_client_test.go
op-e2e/e2eutils/geth/fakeblob.go
op-e2e/e2eutils/geth/fakepos.go
op-e2e/e2eutils/geth/geth.go
op-e2e/e2eutils/setup.go
op-e2e/faultproofs/challenge_preimage_test.go
op-e2e/faultproofs/multi_test.go
op-e2e/faultproofs/output_alphabet_test.go
op-node/flags/flags.go
op-node/node/node.go
op-node/rollup/derive/engine_queue_test.go
op-node/rollup/driver/sequencer_test.go
op-program/client/l2/engineapi/precompiles.go
op-program/client/mpt/db.go
op-program/client/mpt/trie.go

After merging the code from upstream v1.7.2, our CI pipeline failed to pass. This is due to differences in the code on both sides. I modified the test code to make the CI pipeline pass again.
In addition, there are three points worth noting:
1. Due to the differences in code for blob support between the BSC and ETH networks, we do not need a new beaconClient. The previous code only returned nil, but could not pass lint. I directly deleted the relevant code to pass lint.
2. The upstream v1.7.2 code relies on geth version v1.101308.3, while our op-geth repository initially merged code from version v1.101308.2. Although this difference does not affect the core code logic, it will cause the opbnb test code to fail to compile. I temporarily modified the relevant test code to make it compile, …

fix: fix CI after 4844 merge

---

op-node/rollup/derive/engine_queue.go

set `const finalityDelay` to 15 to speed up finality update
speed up finality update
n/a
set `const finalityDelay` to 15 to speed up finality update

op-node: set finalityDelay to 15 to speed up finality update

---

op-node/chaincfg/chains.go

Modify the configuration to add the activation time of the Canyon, delta, and ecotone forks on the Mainnet.
Activation time is as follows:
Shanghai/Canyon Time: 2024-06-20 08:00:00 AM UTC
Delta Time: 2024-06-20 08:10:00 AM UTC
Cancun/Ecotone Time: 2024-06-20 08:20:00 AM UTC
We will activate these hard forks on the mainnet.
none
* Change the mainnet's default configuration to increase the hard fork activation time.

config: Mainnet canyon/delta/ecotone fork time

---

go.mod
go.sum
op-chain-ops/genesis/config.go
op-chain-ops/genesis/genesis.go
op-node/withdrawals/proof.go
op-node/withdrawals/utils.go
packages/contracts-bedrock/scripts/getting-started/config.sh

Add haber fork config in deployment script.
It is convenient for users to enable haber fork when starting a new chain.
Add `haber` hard fork.
* Add `haber` hard fork in deployment script.

feature: add haber fork config in deployment script

---

bedrock-devnet/devnet/__init__.py

After the last merge of upstream code, our Devnet's batcher defaults to submitting blob spanbatch data, but the Delta and Ecotone hard fork configurations were not enabled in the genesis block, causing issues after devnet starts, with the safe block height not increasing. We need to fix this issue.
Enable Delta and Ecotone forks in the Devnet's genesis block so that batchers can submit data of type blob spanbatch.
none
* set l2GenesisDeltaTimeOffset and L2GenesisEcotoneTimeOffset to 0x0

fix(devnet): fork offset should be 0x

---

op-node/rollup/derive/engine_controller.go
op-node/rollup/derive/engine_queue.go
op-service/eth/types.go

This PR is part of the node code for automatically recovering PBSS after an abnormal shutdown. It handles the inconsistent status returned by geth and updates the op-node's unsafe, safe, and finalize markers, as well as synchronizes with geth.
this feature is for automatically recovering PBSS after an abnormal shutdown
N/A

feat: auto recover from pbss geth unclean shutdown

---

bedrock-devnet/devnet/__init__.py
go.mod
go.sum
op-chain-ops/genesis/config.go
op-chain-ops/genesis/genesis.go
packages/contracts-bedrock/scripts/getting-started/config.sh

This PR is made in conjunction with https://github.com/bnb-chain/op-geth/pull/130. A new Wright hard fork has been introduced in op-geth. Whenever there is a new hard fork, we need to make corresponding changes in the genesis file generation code to support the activation of the hard fork through the configuration file.
This modification allows us to configure when to activate the hard fork through the configuration file, which is beneficial for both Devnet and Qanet.
none
* add Wright fork config into genesis file generation code

feat(op-chain-ops): add Wright fork config into genesis file generation code

---

op-chain-ops/cmd/check-derivation/main.go
op-e2e/setup.go
op-node/flags/flags.go
op-node/node/client.go
op-node/service.go
op-service/sources/l1_client.go

This PR includes two changes:
1. Added a configuration item: l1.rpc-max-cache-size, with a default value of 1000. Its value must be greater than or equal to 1. It is recommended that the configured value be greater than or equal to the maximum height difference between the L1 blocks corresponding to the unsafe block height and the safe block height.
2. When the l1 receipts cache is full, log a message to remind the user.
In https://github.com/bnb-chain/opbnb/pull/104, I made modifications to the receipt cache of the L1 client, significantly improving the cache hit rate. However, there are some issues when the safe block height lags far behind the unsafe block height. Firstly, the L1 receipt cache data corresponding to the safe block height is only deleted from the cache after the safe …

feat(op-node): add l1 cache size config

---

op-node/rollup/derive/engine_controller.go
op-service/sources/engine_client.go

When op-geth meet an unexpected shutdown(OOM, forcekill, etc...) and the truncate operation results in the deletion of head data, the block-by-block insertion requests from op-node will trigger an EL sync in geth. This PR addresses this situation.
related geth change: [https://github.com/bnb-chain/op-geth/pull/132](url)
When handling unexpected EL sync triggers, state synchronization is performed based on the specific errors returned by geth.
N/A

(op-node) Keep consistent status when meet an unexpected el sync

---

op-node/chaincfg/chains.go

Modify the configuration to add the activation time of the Fjord hard fork on the Testnet.
Activation time is 2024-09-10 06:00:00 AM UTC.
Modify the configuration to add the activation time of the Fjord hard fork on the Mainnet.
Activation time is 2024-09-24 06:00:00 AM UTC.
We will activate the hard fork on the testnet and mainnet.
None
* Change the testnet and mainnet's default configuration to increase the hard fork activation time.

feature(op-node): add Fjord hard fork time

---

CHANGELOG.md

Update v0.5.0 changelog.
NA
NA
* add fork time
* add L1 fee change reference

doc: update v0.5.0 changelog

---

op-service/sources/l1_client.go

Fixed the issue where the node might get stuck in the l1 client shutdown function when the node is in engine sync mode during shutdown.
When the node has not yet fully synchronized and was in engine sync mode, the `GoOrUpdatePreFetchReceipts` method is not executed. At this time, the done channel of the l1 client has no consumers. If the node is closed at this moment, it will get stuck at the l1 client close operation.
If I simply close the done channel, a `panic: Log in goroutine after Test_xxx has completed` issue will occur during e2e testing. I must ensure that the done channel is truly closed before the close method returns.
none
* Add `preFetchReceiptsClosedChan` to ensure that everything is closed before returning from the Close function
* Add …

fix(op-node): l1 client chan stuck when closed in ELSync mode

---

.github/workflows/docker-release.yml
CHANGELOG.md
op-batcher/Makefile
op-bootnode/Makefile
op-node/Dockerfile
op-node/Makefile
op-proposer/Makefile
op-service/sources/engine_client.go
op-service/sources/l1_client.go

This is a minor release and upgrading is optional.
* fix(ci): support building arm64 architecture by @welkin22 in https://github.com/bnb-chain/opbnb/pull/239
* fix(op-node): l1 client chan stuck when closed in ELSync mode by @welkin22 in https://github.com/bnb-chain/opbnb/pull/241
* fix: add sync status when newpayload API meet the specific error by @krish-nr in https://github.com/bnb-chain/opbnb/pull/240
- ghcr.io/bnb-chain/op-node:v0.5.1
- ghcr.io/bnb-chain/op-batcher:v0.5.1
- ghcr.io/bnb-chain/op-proposer:v0.5.1
**Full Changelog**: https://github.com/bnb-chain/opbnb/compare/v0.5.0...v0.5.1

prepare for v0.5.1

---

op-node/rollup/attributes/attributes.go
op-node/rollup/derive/engine_update.go
op-service/eth/status.go

This PR handles certain specific states to align with the changes in the [sequencer recover feature](https://github.com/bnb-chain/op-geth/pull/166)
related geth [PR](https://github.com/bnb-chain/op-geth/pull/166)
N/A

feat: handle sequencer recover related logic

---

README.md

The previous opstack links are no longer current and have been updated accordingly.
NA
NA
NA

doc: update outdated links in readme

---

op-service/eth/types.go
op-service/sources/engine_client.go

This pr fix error handle of engine_opSealPaylaod api, related fix to op-geth is https://github.com/bnb-chain/op-geth/pull/255
The error handle of original engine_api is chaos and easy lead to bug, the new engine_opSealPayload api followed the original part, and unfortunately triggered bug, which will cause chain stuck if force kill
n/a
extract err stage from rpc error when call engine_opSealPayload api

fix(op-node): extract err stage from rpc error when call engine_opSealPayload api

---

.github/workflows/ci.yml
go.mod
go.sum
op-batcher/batcher/driver.go
op-chain-ops/cmd/check-derivation/main.go
op-e2e/actions/l2_batcher.go
op-e2e/actions/l2_batcher_test.go
op-e2e/actions/span_batch_test.go
op-e2e/actions/sync_test.go
op-e2e/brotli_batcher_test.go
op-e2e/eip4844_test.go
op-node/rollup/derive/span_batch_tx.go
op-node/rollup/derive/span_batch_txs.go
op-program/client/mpt/db.go
op-service/sources/eth_client.go

adapt BSC Prague fork
adapt BEP-441 and EIP-7702
N/A
* update geth dependency 
* automatically use the len(validators) of BSC network

feat: EIP-7702 adaption

---

op-batcher/batcher/channel_manager.go
op-chain-ops/genesis/config.go
op-node/p2p/host_test.go
op-node/rollup/derive/attributes.go
op-node/rollup/derive/batch_queue_test.go
op-node/rollup/derive/batches.go
op-node/rollup/derive/channel_out.go
op-node/rollup/derive/engine_update.go
op-node/rollup/driver/sequencer.go
op-service/eth/types.go

Refine l2 attribute millisecond timestamp setter
Resue first two bytes of PrevRandao to represent the milli part of the L2 timestamp.
N/A
* attribute setter func.

chore: refine l2 attribute millisecond timestamp setter

---

op-batcher/batcher/channel_manager.go
op-node/rollup/derive/l2block_util.go

Fix channel manager l2 milli-part parse.
L1 milli-part timestamp is stored by mix-digest highest 2 bytes.
N/A.
* batcher l2 milli-part parse.

fix: fix channel manager l2 milli-part parse

---

op-node/rollup/derive/span_batch.go

Fix batcher reltime wrong calculate method.
N/A.
N/A.
* N/A.

fix: fix batcher reltime wrong calculate method

---

packages/contracts-bedrock/src/L1/L2OutputOracle.sol
packages/contracts-bedrock/test/L1/L2OutputOracle.t.sol

L2OutputOracle uses millisecond to compute l2 timestamp after Volta Hardfork.
Current opBNB block time is 1s per block. After Volta Hardfork, opBNB block time is 500ms per block. `L2OutputOracle.sol` contract computes l2 timestamp by l2BlockNumber which is not right after Volta Hardfork. Therefore, add `computeL2TimestampAfterVolta` function to compute new l2 timestamp.
N/A
* `l2MillisecondsBlockTime` constant is used to record new l2 block time.
* `voltaBlockNumber` constant is used to record hardfork block number.
* `isL2TimestampValid` function is used to verify the computed l2 timestamp is valid.
* `computeL2TimestampAfterVolta` function is used to new  l2 timestamp.

feat: L2OutputOracle uses millisecond to compute l2 timestamp after volta hardfork

---

op-node/rollup/derive/attributes.go
op-service/eth/types.go

The op-node writes the BlockInterval into the third byte of the `PrevRandao` in `PayloadAttributes`, with each unit representing 500ms.
op-geth has more control over block time. Previously, if the BlockTime configuration of op-node was greater than 1 second, the excess time would be wasted.
[op-geth](https://github.com/bnb-chain/op-geth/pull/279)
NO.
NO.

feat: set block interval to engine api

---

go.mod
go.sum

Update op-geth dependency for adapt new l1 hash cal.
Refer to https://github.com/bnb-chain/op-geth/pull/284.
N/A.
* op-geth dependency.

chore: update op-geth dependency for adapt new l1 hash cal
