- .github/workflows/docker-release.yml
- op-e2e/actions/l2_verifier.go
- op-e2e/setup.go
- op-e2e/system_adminrpc_test.go
- op-e2e/system_test.go
- op-node/flags/flags.go
- op-node/node/api.go
- op-node/node/config.go
- op-node/node/config_persistence.go
- op-node/node/config_persistence_test.go
- op-node/node/node.go
- op-node/node/server_test.go
- op-node/rollup/driver/driver.go
- op-node/rollup/driver/state.go
- op-node/service.go
- op-node/sources/rollupclient.go
merged official pr
1. op-node active state persistence   
https://github.com/ethereum-optimism/optimism/pull/6105
2. op-node add API: SequencerActive,  whether op-node is active
https://github.com/ethereum-optimism/optimism/pull/6190
> feat: support persist active api

- .github/workflows/docker-release.yml
cherry pick from https://github.com/bnb-chain/opbnb/pull/11
> ci: add release docker images workflow

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE.md
Add issue and pull request templates.
To enhance the context for pull requests and issues.
NA
NA
> chore: add issue and pull request templates

- CHANGELOG.md
Add v0.2.1 changelog.
NA
NA
NA
> doc: add v0.2.1 changelog

- CHANGELOG.md
Add v0.2.4 changelog.
NA
NA
NA
> doc: add v0.2.4 changelog

- CHANGELOG.md
Update v0.2.4 changelog.
NA
NA
NA
> doc: update v0.2.4 changelog

- op-chain-ops/genesis/config.go
Change genesis basefee with `fermat`.
N/A
N/A
Change genesis basefee with `fermat`.
> fix(op-node): fix basefee when start new chain with fermat

- CHANGELOG.md
add v0.3.0 changelog
prepare for next release
n/a
add v0.3.0 changelog
> chore: add v0.3.0 changelog

- CHANGELOG.md
update v0.3.0 changelog.md
update v0.3.0 changelog.md
n/a
update v0.3.0 changelog.md
> chore: update v0.3.0 changelog.md

- .github/ISSUE_TEMPLATE/bug.md
- .github/workflows/close-stale.yml
Adjust stale action and fix issue template typo.
It's better to automatically close inactive issues and keep pull requests for manual review and closure.
NA
* NA
> chore: adjust stale action and fix issue template typo

- CHANGELOG.md
- op-node/chaincfg/chains.go
Postone the Snow hardfork time to Apr-15-2024 06 AM +UTC.
NA
NA
* NA
> postpone snowfork time

- CHANGELOG.md
Update v0.3.3 changlog.
NA
NA
NA
> doc: update v0.3.3 changelog

- op-node/chaincfg/chains.go
Update qanet config.
Update qanet config for test.
N/A.
* Update qanet rollup config.
> feature(op-node): update qanet config

- CHANGELOG.md
Add changelogs to v0.4.3.
NA
NA
NA
> doc: add changelogs to v0.4.3

- CHANGELOG.md
Add v0.5.0 change log
Add v0.5.0 change log
n/a
> chore: add v0.5.0 changelog

- CHANGELOG.md
Add changelogs to v0.5.1.
NA
NA
NA
> doc: add changelogs to v0.5.1

- CHANGELOG.md
Add change log to v0.5.2
NA
NA
NA
> doc: add changelogs to v0.5.2

- CHANGELOG.md
add eip 7702 item to v0.5.2 changelog
No.
No.
No.
> doc: add eip 7702 item to v0.5.2 changelog

- packages/contracts-bedrock/src/L1/L2OutputOracle.sol
Revert contract changes from https://github.com/bnb-chain/opbnb/pull/265/commits/374a5c7874e07fc33ae744e4632251813c59d546,
The contract does not need to be changed.
N/A.
* Revert contract change.
> revert: revert contract change

- op-node/rollup/derive/payload_util.go
- op-service/eth/id.go
- op-service/eth/types.go
Fix some timestamp bug by self test
tell us why we need these changes...
add an example CLI or API response...
* add each change in a bullet point here
* ...
> chore: fix some timestamp bug by self test

- op-node/rollup/chain_spec.go
- op-node/rollup/types.go
Remove volta hard fork from chain spec.
NO.
NO.
NO.
> chore: remove volta hard fork from chain spec

- op-node/rollup/chain_spec.go
- op-node/rollup/types.go
Add check for the fork order, specifically volta hard fork.
No.
No.
No.
> fix: volta hard fork order check

- CHANGELOG.md
- op-node/chaincfg/chains.go
Add v0.5.3 changelog
No.
No.
No.
> doc: add v0.5.3 changelog

- op-node/rollup/derive/span_batch.go
- op-node/rollup/types.go
Fix bug that set volta time from genesis 
NO.
NO.
NO.
> fix: set volta time from genesis

- op-node/rollup/types.go
Fix genesis volta related helper function.
```go
func (c *Config) VoltaBlockNumber() uint64 {
if c.VoltaTime == nil || *c.VoltaTime == 0 {
return 0
}
return (*c.VoltaTime-c.Genesis.L2Time)/c.BlockTime + c.Genesis.L2.Number
}
``` 
The VoltaBlockNumber() function originally returned 0, indicating that Volta fork was not set. However, the current support for genesis block as Volta fork (block height is 0 for genesis block), so this semantics is wrong.
N/A.
* volta related helper funcs.
> fix: fix genesis volta related helper function

- go.mod
- go.sum
- op-batcher/batcher/driver.go
- op-chain-ops/cmd/check-derivation/main.go
- op-challenger/game/keccak/fetcher/fetcher_test.go
- op-e2e/actions/l2_batcher.go
- op-e2e/actions/l2_batcher_test.go
- op-e2e/actions/span_batch_test.go
- op-e2e/actions/sync_test.go
- op-e2e/brotli_batcher_test.go
- op-e2e/eip4844_test.go
- op-node/cmd/genesis/cmd.go
- op-node/rollup/derive/channel_out_test.go
- op-node/rollup/derive/test/random.go
- op-program/client/l2/oracle.go
- op-wheel/engine/engine.go
Update stateless geth deps.
N/A.
N/A.
* go.mod.
> chore: adapt stateless deps

- op-batcher/Dockerfile
- op-bootnode/Dockerfile
- op-node/Dockerfile
- op-proposer/Dockerfile
container run as none root
tell us why we need these changes...
add an example CLI or API response...
* add each change in a bullet point here
* ...
> Run as none root develop

- op-batcher/Dockerfile
- op-bootnode/Dockerfile
- op-node/Dockerfile
- op-proposer/Dockerfile
add a description of your changes here...
tell us why we need these changes...
add an example CLI or API response...
* add each change in a bullet point here
* ...
> feat: run as none rot
